credentials:
  usernames:
    admin:
      email: hhadmin@yopmail.com
      name: Admin 
      password: $2b$12$WNL5ZP27A9FHxabEt4Th4uiLsz55ZTtfst3d3fLtSyf228WqBVhtG
cookie:
  expiry_days: 30
  key: auth_key # Must be string
  name: healthcare_app
preauthorized:
  emails:
  - hhadmin@yopmail.com